---
title: "Labor market"
author: "Istvan Konya"
output: html_document
---

## Introduction

Start with some basic housekeeping: load packages, define colors.

```{r include=FALSE}

library(tidyverse)
library(eurostat)
library(zoo)

# Define my favorite color scheme
col1 = "#013C58"
col3 = "#800000"
col2 = "#E69C38"
col5 = "#808000"
col4 = "#C0C0C0"
col6 = "#7093DB"
cols = c(col1,col2,col3,col4,col5,col6)

eu <- c("AT","BE","DK","DE","EL","ES","FR","IT","CY","MT","NL","PT","FI","SE",
        "CZ","HU","PL","SK","RO","BG","SI","HR","EE","LT","LV","LU","IE")
```

## Quarterly data

Not seasonally adjusted, because the relevant auxiliary measures are also not adjusted.

#### Stocks

```{r warning=FALSE, message=FALSE}

df <- get_eurostat("lfsq_pganws",filters=list(age="Y15-74",geo=eu,citizen="TOTAL",
                                                 sex="T",wstatus=c("EMP","UNE","INAC")))
df <- df %>% pivot_wider(id_cols=c(geo,time),names_from=wstatus,values_from=values)
df <- df %>% mutate(time=as.yearqtr(time))
```

#### Duration and tenure

```{r warning=FALSE, message=FALSE}

dur <- get_eurostat("lfsq_ugad", filters = list(geo=eu,duration=c("M_LT1","M1-2"),
                                                age="Y15-74",sex="T"))
dur <- dur %>% pivot_wider(id_cols = c(geo,time), names_from = duration,
                           values_from = values)
dur <- dur %>% mutate(unes = `M_LT1`+`M1-2`) %>% select(geo,time,unes)
dur$time <- as.yearqtr(dur$time)

ten <- get_eurostat("lfsq_egdn2", filters = list(geo=eu,duration="M_LT3",nace_r2="TOTAL",
                                                age="Y15-74",sex="T"))
ten <- ten %>% select(geo,time,emps = values)
ten$time <- as.yearqtr(ten$time)

df <- df %>% left_join(dur)
df <- df %>% left_join(ten)
```

#### Transitions

```{r warning=FALSE, message=FALSE}

tran <- get_eurostat("lfsi_long_q",
                     filters = list(unit = "THS_PER", s_adj = "NSA", geo = eu,
                                    sex = "T"))
tran$time <- as.yearqtr(tran$time)
tran <- tran %>% pivot_wider(id_cols=c(geo,time),names_from="indic_em",values_from=values)
```

## Annual data

#### Stocks

```{r warning=FALSE, message=FALSE}

dfa <- get_eurostat("lfsa_pganws", time_format = "num",
                    filters=list(age="Y15-74",geo=eu,citizen="TOTAL",
                                 sex="T",wstatus=c("EMP","UNE","INAC")))
dfa <- dfa %>% pivot_wider(id_cols=c(geo,time),names_from=wstatus,values_from=values)
```

#### Job tenure
